name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: rprunnerself

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag rpimages:$(date +%s)
    
    - name: Release of the GitHub Actions Runner
      run:  |
       uname -a
       cat /etc/issue
       touch rpneww.txt
   
    - name: Build the Docker image
      run: |
       docker images
       docker ps -a
